### ISSUE TITLE
Where to publish

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/nounou#12]
The following text is signed using my public PGP key which you have received by e-mail by now. It is also available online from pastebin [here](http://pastebin.com/SSb3NGtS)
You can use it to verify the signature of my message below

@ktakagaki 

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Where would you like to publish Nounou as configuring/refactoring the SBT parts of Nounou? It is possible to publish both on [Maven repositories](http://mvnrepository.com/) and also [SonaType](http://www.sonatype.com/) and other public repositories.

Where do you have account (and what are your login names, now pwds, just your public account info)? and which places would you like to publish?

[General Publishing in SBT](http://www.scala-sbt.org/0.13/docs/Publishing.html)
[Specifically publishing/deploying to SonaType in SBT](http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html)
[SBT based publishing/deploying to Plexus](http://www.cakesolutions.net/teamblogs/2012/01/28/publishing-sbt-projects-to-nexus)
[General SonaType Publishing Information](http://central.sonatype.org/pages/ossrh-guide.html)

I expect to register an account for SonaType some time this week. I have also spend some good amount of energy making myself my new "All in one" public PGP key which I intend to use from now on for all signing and encrypting of messages and binary files.
This I will use with the SBT-PGP plugin. The Public PGP key will be e-mailed to you later, and it also has a profile picture of me embedded into it
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWrxoLAAoJEHmWhfKhCnpKDE8QAInZbLNAzZbezYIdU55/d2mA
ibM7BY7GfGM0BFvX5GjgLQmkHQKJBESUsKaqcKPi821RfuEodR2P61eP55eOtVwQ
BV1TYbucktdnNARYT5N+AlVlV/9pflFwk9txmU7rv0i74F7ni1bmFKULjeMYyuDV
OIZEEmIeK90ilhE95i0YGmLw1wee9ZMZDRtPc7SRBqtWUYSiKKarEd4KcdZo+HBU
wbmiU6nePIaumvlkcM5RgY5kppjwLN39BwTMmof5Z29xpQDX+QdOUwGBfaytLL/D
FqbqJSbXfUQe9wwX70lNBlBmG1eOCgzHCi/Kn5QlqsVQ65l5IY3mZ2T9fsDoxILX
tHCsx1TuZFpogDDBgNFAzPUGE/hhVzLkP8jNoDoINip2cRAThOoYu02uS41dzHXz
AaUBb4beD9qD79VJvQSVwV9FduflDx41K+kFAY9arys5J7h/FB9yymkZpCkrakm8
FggUchBGpKUblVRqfZHDkyN8rDrA9omcPqHDO8WWvQkZ5dlSxCJsWCAZkUNmGdeL
oW3vpDerQfY0hrifIHTfUYUKvRs1tmj+7PEMIzVyOQHP/2zjY9FKFIhX+PSzav2Z
Kf9K3WKDuh24qm3PAhSgeH+qDL8mecTAbR8r2kOXesDcagT5T6VtAz2hjElwSNmR
2D3QGxdCFgl/Zdo3iU/c
=R+nJ
-----END PGP SIGNATURE-----

**Comment by ktakagaki** [comment]
SonaType is probably OK, it's used a lot. I haven't really thought about it or made any accounts.
