### ISSUE TITLE
Open Issue and specify reward milestones for slentzen/nounou fork

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/nounou#5]
As previously mentioned.
Open an Issue request for each specific task to complete and shortly describe what to achieve on my fork of your nounou repository.

Also, which branch of your own ktakagaki/breeze repository should I add as a managed dependency using SBT here in nounou? Should I use the master branch, or any of the numerous other branches?

I have forked all of your repositories now, nounou, breeze, and hopefully GitHub will link up Hayabaya by tomorrow. If they don't, I'll do as we discussed and just re-fork your repository and copy over the code.

@ktakagaki

**Comment by ktakagaki** [comment]
1. Can do

2. Hmm, are you not seeing the "nounou" branch on ktakagaki/breeze? Or perhaps it's confusing because the branch is the name of another repo?

3. OK, or maybe email them again, support might note be reading carefully and it would be nice to have all the Github stuff like issues merged

**Comment by slentzen** [comment]
I am seeing the branches just fine now

Which branch should I use?
![breezebranches](https://cloud.githubusercontent.com/assets/6833446/12676343/b1c69044-c691-11e5-8da0-0da4ecb1da16.jpg)

**Comment by ktakagaki** [comment]
That looks great. Somehow, you aren't seeing branch "nounou"....
could you try again?
https://github.com/ktakagaki/breeze/tree/nounou

**Comment by slentzen** [comment]
Now I am. I have no idea why, but previously that branch wasn't visible for me so I didn't know it existed.

**Comment by ktakagaki** [comment]
I finally got around to deleting some old dev branches, maybe the plugin can handle only 20 branches (or that's default)...

**Comment by slentzen** [comment]
I haven't seen 20 mentioned anywhere as a hard limit but it would make sense
