### ISSUE TITLE
Unable to create milestones

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/nounou#6]
I don't know if it's because I'm using the new version of GitHub and it's still beta, or if it's because the feature has to be enabled. But I'm unable to create milestones under the "Issues" tab on this repository as shown her
https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/

@ktakagaki

**Comment by ktakagaki** [comment]
OK, for this one, I can make you a collaborator

**Comment by ktakagaki** [comment]
@slentzen 
Does it work? I can get to that on your repo...

![image](https://cloud.githubusercontent.com/assets/4279323/12630932/2e249968-c54f-11e5-9d8b-11c87f0494ba.png)

![image](https://cloud.githubusercontent.com/assets/4279323/12630956/48ad1ba2-c54f-11e5-8d91-0d8767ea09d1.png)

**Comment by slentzen** [comment]
yes works now
