### ISSUE TITLE
SBT refactor (SL: 2016.02.01)

### ISSUE THREAD

**Issue by ktakagaki** [ktakagaki/nounou#7]
Refactor SBT files to depend on branch "nounou" of ktakagaki/breeze/ instead of ../lib/math.jar and build successfully in SBT without .idea info.

**Comment by ktakagaki** [comment]
@slentzen, "issues" not open to me on your nounou fork

**Comment by slentzen** [comment]
Roger. Will check if you are added as a collaborator now.
Thanks for adding the specific issues. I know we discussed it all before, but it's nice to have et explicitly written the places I have to remember to do it.

Will also make it easy to retroactively keep track of which milestones have been reached at the end of the month. Todoist removes the points when they are finished, here we can always see them, and maybe I can also do a git blame on the feature branches.

@ktakagaki

**Comment by ktakagaki** [comment]
Good point re Todoist

**Comment by slentzen** [comment]
@ktakagaki 
Can you confirm regarding the PR I did on this issue? I'm back looking at SBT today and going through the docs trying to proceed with the next steps

**Comment by slentzen** [comment]
@ktakagaki 
Issue now fully solved on your latest master branch. Using your k/bree#nounou branch
